name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment.prod.ts
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          GIITH_CLIENT_ID: ${{ secrets.GIITH_CLIENT_ID }}
          GIITH_CLIENT_APP_ID: ${{ secrets.GIITH_CLIENT_APP_ID }}
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.prod.ts << EOF
          export const environment = {
            production: true,
            githubClientId: '${GIITH_CLIENT_ID}',
            githubClientAppId: '${GIITH_CLIENT_APP_ID}',
            useMockData: false,
            apiUrl: '${API_BASE_URL}'
          };
          EOF

      - name: Build (production)
        env:
          PRESERVE_ENV_FILES: "true"
        run: npm run build -- --configuration production
